/**
 * Dünya Kupası tarihsel verileri için statik lookup tablosu.
 * Scraping 403 hatası verdiği için, WC tarihi değişmediğinden statik veri daha güvenilir.
 */
import type { WorldFootballData } from '../types';

const FINISH_PRIORITY = ['Şampiyon', 'İkinci', 'Üçüncü', 'Dördüncü', 'Çeyrek Final', 'Yarı Final', 'Son 16', 'Grup Aşaması'];

const WC_HISTORY: Record<string, { year: number; finish: string }[]> = {
  'türkiye': [
    { year: 1954, finish: 'Grup Aşaması' },
    { year: 2002, finish: 'Üçüncü' },
  ],
  'turkey': [
    { year: 1954, finish: 'Grup Aşaması' },
    { year: 2002, finish: 'Üçüncü' },
  ],
  'brezilya': [
    { year: 1930, finish: 'Grup Aşaması' },
    { year: 1934, finish: 'İlk Tur' },
    { year: 1938, finish: 'Üçüncü' },
    { year: 1950, finish: 'İkinci' },
    { year: 1954, finish: 'Çeyrek Final' },
    { year: 1958, finish: 'Şampiyon' },
    { year: 1962, finish: 'Şampiyon' },
    { year: 1966, finish: 'Grup Aşaması' },
    { year: 1970, finish: 'Şampiyon' },
    { year: 1974, finish: 'Dördüncü' },
    { year: 1978, finish: 'Üçüncü' },
    { year: 1982, finish: 'Son 16' },
    { year: 1986, finish: 'Çeyrek Final' },
    { year: 1990, finish: 'Son 16' },
    { year: 1994, finish: 'Şampiyon' },
    { year: 1998, finish: 'Dördüncü' },
    { year: 2002, finish: 'Şampiyon' },
    { year: 2006, finish: 'Son 16' },
    { year: 2010, finish: 'Çeyrek Final' },
    { year: 2014, finish: 'Dördüncü' },
    { year: 2018, finish: 'Çeyrek Final' },
    { year: 2022, finish: 'Çeyrek Final' },
  ],
  'brazil': [
    { year: 1930, finish: 'Grup Aşaması' },
    { year: 1958, finish: 'Şampiyon' },
    { year: 1962, finish: 'Şampiyon' },
    { year: 1970, finish: 'Şampiyon' },
    { year: 1994, finish: 'Şampiyon' },
    { year: 2002, finish: 'Şampiyon' },
    { year: 2022, finish: 'Çeyrek Final' },
  ],
  'almanya': [
    { year: 1934, finish: 'Üçüncü' },
    { year: 1938, finish: 'İlk Tur' },
    { year: 1954, finish: 'Şampiyon' },
    { year: 1958, finish: 'Dördüncü' },
    { year: 1962, finish: 'Çeyrek Final' },
    { year: 1966, finish: 'İkinci' },
    { year: 1970, finish: 'Üçüncü' },
    { year: 1974, finish: 'Şampiyon' },
    { year: 1978, finish: 'İkinci Tur' },
    { year: 1982, finish: 'İkinci' },
    { year: 1986, finish: 'İkinci' },
    { year: 1990, finish: 'Şampiyon' },
    { year: 1994, finish: 'Çeyrek Final' },
    { year: 1998, finish: 'Çeyrek Final' },
    { year: 2002, finish: 'İkinci' },
    { year: 2006, finish: 'Üçüncü' },
    { year: 2010, finish: 'Üçüncü' },
    { year: 2014, finish: 'Şampiyon' },
    { year: 2018, finish: 'Grup Aşaması' },
    { year: 2022, finish: 'Grup Aşaması' },
  ],
  'germany': [{ year: 1954, finish: 'Şampiyon' }, { year: 1974, finish: 'Şampiyon' }, { year: 1990, finish: 'Şampiyon' }, { year: 2014, finish: 'Şampiyon' }, { year: 2022, finish: 'Grup Aşaması' }],
  'fransa': [
    { year: 1930, finish: 'Grup Aşaması' },
    { year: 1934, finish: 'İlk Tur' },
    { year: 1938, finish: 'Çeyrek Final' },
    { year: 1954, finish: 'Grup Aşaması' },
    { year: 1958, finish: 'Üçüncü' },
    { year: 1966, finish: 'Grup Aşaması' },
    { year: 1978, finish: 'Grup Aşaması' },
    { year: 1982, finish: 'Dördüncü' },
    { year: 1986, finish: 'Üçüncü' },
    { year: 1998, finish: 'Şampiyon' },
    { year: 2002, finish: 'Grup Aşaması' },
    { year: 2006, finish: 'İkinci' },
    { year: 2010, finish: 'Grup Aşaması' },
    { year: 2014, finish: 'Çeyrek Final' },
    { year: 2018, finish: 'Şampiyon' },
    { year: 2022, finish: 'İkinci' },
  ],
  'france': [{ year: 1998, finish: 'Şampiyon' }, { year: 2018, finish: 'Şampiyon' }, { year: 2022, finish: 'İkinci' }],
  'arjantin': [
    { year: 1930, finish: 'İkinci' },
    { year: 1934, finish: 'İlk Tur' },
    { year: 1958, finish: 'Grup Aşaması' },
    { year: 1962, finish: 'Grup Aşaması' },
    { year: 1966, finish: 'Çeyrek Final' },
    { year: 1974, finish: 'İkinci Tur' },
    { year: 1978, finish: 'Şampiyon' },
    { year: 1982, finish: 'İkinci Tur' },
    { year: 1986, finish: 'Şampiyon' },
    { year: 1990, finish: 'İkinci' },
    { year: 1994, finish: 'Son 16' },
    { year: 1998, finish: 'Çeyrek Final' },
    { year: 2002, finish: 'Grup Aşaması' },
    { year: 2006, finish: 'Çeyrek Final' },
    { year: 2010, finish: 'Çeyrek Final' },
    { year: 2014, finish: 'İkinci' },
    { year: 2018, finish: 'Son 16' },
    { year: 2022, finish: 'Şampiyon' },
  ],
  'argentina': [{ year: 1978, finish: 'Şampiyon' }, { year: 1986, finish: 'Şampiyon' }, { year: 2022, finish: 'Şampiyon' }],
  'ispanya': [
    { year: 1934, finish: 'Çeyrek Final' },
    { year: 1950, finish: 'Dördüncü' },
    { year: 1962, finish: 'Grup Aşaması' },
    { year: 1966, finish: 'Çeyrek Final' },
    { year: 1978, finish: 'Grup Aşaması' },
    { year: 1982, finish: 'İkinci Tur' },
    { year: 1986, finish: 'Çeyrek Final' },
    { year: 1990, finish: 'Son 16' },
    { year: 1994, finish: 'Çeyrek Final' },
    { year: 1998, finish: 'Son 16' },
    { year: 2002, finish: 'Çeyrek Final' },
    { year: 2006, finish: 'Son 16' },
    { year: 2010, finish: 'Şampiyon' },
    { year: 2014, finish: 'Grup Aşaması' },
    { year: 2018, finish: 'Son 16' },
    { year: 2022, finish: 'Son 16' },
  ],
  'spain': [{ year: 2010, finish: 'Şampiyon' }, { year: 2022, finish: 'Son 16' }],
  'İngiltere': [
    { year: 1950, finish: 'Grup Aşaması' },
    { year: 1954, finish: 'Çeyrek Final' },
    { year: 1958, finish: 'Grup Aşaması' },
    { year: 1962, finish: 'Çeyrek Final' },
    { year: 1966, finish: 'Şampiyon' },
    { year: 1970, finish: 'Çeyrek Final' },
    { year: 1982, finish: 'İkinci Tur' },
    { year: 1986, finish: 'Çeyrek Final' },
    { year: 1990, finish: 'Dördüncü' },
    { year: 1998, finish: 'Son 16' },
    { year: 2002, finish: 'Çeyrek Final' },
    { year: 2006, finish: 'Çeyrek Final' },
    { year: 2010, finish: 'Son 16' },
    { year: 2014, finish: 'Grup Aşaması' },
    { year: 2018, finish: 'Dördüncü' },
    { year: 2022, finish: 'Çeyrek Final' },
  ],
  'england': [{ year: 1966, finish: 'Şampiyon' }, { year: 2022, finish: 'Çeyrek Final' }],
  'portekiz': [
    { year: 1966, finish: 'Üçüncü' },
    { year: 1986, finish: 'Grup Aşaması' },
    { year: 2002, finish: 'Grup Aşaması' },
    { year: 2006, finish: 'Dördüncü' },
    { year: 2010, finish: 'Son 16' },
    { year: 2014, finish: 'Grup Aşaması' },
    { year: 2018, finish: 'Çeyrek Final' },
    { year: 2022, finish: 'Dördüncü' },
  ],
  'portugal': [{ year: 1966, finish: 'Üçüncü' }, { year: 2022, finish: 'Dördüncü' }],
  'hollanda': [
    { year: 1934, finish: 'İlk Tur' },
    { year: 1938, finish: 'Çeyrek Final' },
    { year: 1974, finish: 'İkinci' },
    { year: 1978, finish: 'İkinci' },
    { year: 1990, finish: 'Son 16' },
    { year: 1994, finish: 'Çeyrek Final' },
    { year: 1998, finish: 'Dördüncü' },
    { year: 2006, finish: 'Son 16' },
    { year: 2010, finish: 'İkinci' },
    { year: 2014, finish: 'Üçüncü' },
    { year: 2022, finish: 'Çeyrek Final' },
  ],
  'netherlands': [{ year: 1974, finish: 'İkinci' }, { year: 1978, finish: 'İkinci' }, { year: 2010, finish: 'İkinci' }, { year: 2022, finish: 'Çeyrek Final' }],
  'belçika': [
    { year: 1930, finish: 'Grup Aşaması' },
    { year: 1934, finish: 'İlk Tur' },
    { year: 1938, finish: 'Grup Aşaması' },
    { year: 1954, finish: 'Grup Aşaması' },
    { year: 1970, finish: 'Grup Aşaması' },
    { year: 1982, finish: 'İkinci Tur' },
    { year: 1986, finish: 'Dördüncü' },
    { year: 1990, finish: 'Son 16' },
    { year: 1994, finish: 'Son 16' },
    { year: 1998, finish: 'Son 16' },
    { year: 2002, finish: 'Son 16' },
    { year: 2014, finish: 'Çeyrek Final' },
    { year: 2018, finish: 'Üçüncü' },
    { year: 2022, finish: 'Grup Aşaması' },
  ],
  'belgium': [{ year: 2018, finish: 'Üçüncü' }, { year: 2022, finish: 'Grup Aşaması' }],
  'italya': [
    { year: 1934, finish: 'Şampiyon' },
    { year: 1938, finish: 'Şampiyon' },
    { year: 1950, finish: 'Grup Aşaması' },
    { year: 1954, finish: 'Grup Aşaması' },
    { year: 1962, finish: 'Grup Aşaması' },
    { year: 1966, finish: 'Grup Aşaması' },
    { year: 1970, finish: 'İkinci' },
    { year: 1974, finish: 'Grup Aşaması' },
    { year: 1978, finish: 'Dördüncü' },
    { year: 1982, finish: 'Şampiyon' },
    { year: 1986, finish: 'Son 16' },
    { year: 1990, finish: 'Üçüncü' },
    { year: 1994, finish: 'İkinci' },
    { year: 1998, finish: 'Çeyrek Final' },
    { year: 2002, finish: 'Son 16' },
    { year: 2006, finish: 'Şampiyon' },
    { year: 2010, finish: 'Grup Aşaması' },
    { year: 2014, finish: 'Grup Aşaması' },
  ],
  'italy': [{ year: 1934, finish: 'Şampiyon' }, { year: 1938, finish: 'Şampiyon' }, { year: 1982, finish: 'Şampiyon' }, { year: 2006, finish: 'Şampiyon' }],
  'japonya': [
    { year: 1998, finish: 'Grup Aşaması' },
    { year: 2002, finish: 'Son 16' },
    { year: 2006, finish: 'Grup Aşaması' },
    { year: 2010, finish: 'Son 16' },
    { year: 2014, finish: 'Grup Aşaması' },
    { year: 2018, finish: 'Son 16' },
    { year: 2022, finish: 'Son 16' },
  ],
  'japan': [{ year: 2022, finish: 'Son 16' }],
  'fas': [
    { year: 1970, finish: 'Grup Aşaması' },
    { year: 1986, finish: 'Son 16' },
    { year: 1994, finish: 'Grup Aşaması' },
    { year: 1998, finish: 'Grup Aşaması' },
    { year: 2018, finish: 'Grup Aşaması' },
    { year: 2022, finish: 'Dördüncü' },
  ],
  'morocco': [{ year: 2022, finish: 'Dördüncü' }],
  'meksika': [
    { year: 1930, finish: 'Grup Aşaması' },
    { year: 1950, finish: 'Grup Aşaması' },
    { year: 1954, finish: 'Grup Aşaması' },
    { year: 1958, finish: 'Grup Aşaması' },
    { year: 1962, finish: 'Grup Aşaması' },
    { year: 1966, finish: 'Grup Aşaması' },
    { year: 1970, finish: 'Çeyrek Final' },
    { year: 1978, finish: 'Grup Aşaması' },
    { year: 1986, finish: 'Çeyrek Final' },
    { year: 1994, finish: 'Son 16' },
    { year: 1998, finish: 'Son 16' },
    { year: 2002, finish: 'Son 16' },
    { year: 2006, finish: 'Son 16' },
    { year: 2010, finish: 'Son 16' },
    { year: 2014, finish: 'Son 16' },
    { year: 2018, finish: 'Son 16' },
    { year: 2022, finish: 'Grup Aşaması' },
  ],
  'mexico': [{ year: 2022, finish: 'Grup Aşaması' }],
  'abd': [
    { year: 1930, finish: 'Üçüncü' },
    { year: 1934, finish: 'İlk Tur' },
    { year: 1950, finish: 'Grup Aşaması' },
    { year: 1990, finish: 'Grup Aşaması' },
    { year: 1994, finish: 'Son 16' },
    { year: 1998, finish: 'Grup Aşaması' },
    { year: 2002, finish: 'Çeyrek Final' },
    { year: 2006, finish: 'Grup Aşaması' },
    { year: 2010, finish: 'Son 16' },
    { year: 2014, finish: 'Son 16' },
    { year: 2022, finish: 'Son 16' },
  ],
  'usa': [{ year: 2022, finish: 'Son 16' }],
};

export async function scrapeWorldFootball(team: string): Promise<import('../types').WorldFootballData | null> {
  const key = team.toLowerCase();
  const history = WC_HISTORY[key];

  if (!history || history.length === 0) {
    console.warn(`[WorldFootball] "${team}" için statik WC verisi bulunamadı.`);
    return null;
  }

  const sorted = [...history].sort((a, b) => a.year - b.year);
  const titles = sorted.filter((h) => h.finish === 'Şampiyon').length;
  const firstAppearance = sorted[0]?.year ?? null;

  let bestFinish = 'Bilinmiyor';
  for (const p of FINISH_PRIORITY) {
    if (sorted.some((h) => h.finish === p)) { bestFinish = p; break; }
  }

  return {
    history: sorted,
    titles,
    bestFinish,
    totalAppearances: sorted.length,
    firstAppearance,
  };
}
